### ISSUE TITLE
How to make the extension work on Ask Ubuntu?

### ISSUE THREAD

**Issue by orschiro** [oliversalzburg/se-kbd-button#3]
Dear @oliversalzburg,

Thank you so much for your extension!

I came to you from https://meta.askubuntu.com/questions/16055/add-icon-to-the-composing-editor-to-format-keyboard-shortcuts. 

I installed the extension but do not see a button on Ask Ubuntu. 

Can you help me, please?

Thankfully,

-Robert

![image](https://cloud.githubusercontent.com/assets/170947/18358961/fa1c945e-75f7-11e6-8f98-88671ab4f988.png)

**Comment by oliversalzburg** [comment]
Well, it actually *should* work out of the box, but this project has not been maintained in a while.

**Comment by oliversalzburg** [comment]
Works for me actually
![image](https://cloud.githubusercontent.com/assets/1658949/18365338/9efb46c2-7612-11e6-81f4-4b8e0f2c9d99.png)

**Comment by orschiro** [comment]
Thanks for your reply!

Do you have any idea why it doesn't show up for me?

-Robert

**Comment by oliversalzburg** [comment]
None whatsoever :( Anything in the DevTools console?

**Comment by orschiro** [comment]
Dear @oliversalzburg,

Are you referring to the following interface?

Warmly,

-Robert

![image](https://cloud.githubusercontent.com/assets/170947/18474072/7ccfa64a-79c0-11e6-8c02-588584791a7c.png)

**Comment by oliversalzburg** [comment]
Yeah, that looks just fine. Maybe it conflicts with another extension, but I would expect to see some information in the console.

**Comment by orschiro** [comment]
We might need some extra help debugging, I guess. 

![image](https://cloud.githubusercontent.com/assets/170947/18485683/264a04a4-79ee-11e6-9caf-77a856518abb.png)

Source: https://meta.askubuntu.com/questions/16055/add-icon-to-the-composing-editor-to-format-keyboard-shortcuts/16058?noredirect=1#comment31834_16058

Warmly,

-Robert

**Comment by oliversalzburg** [comment]
Help would definitely appreciated. In the meantime, maybe you can use the [userscript](https://github.com/oliversalzburg/se-kbd-button/blob/master/dist/se-kbd-button.user.js) with an extension like Tampermonkey. See if that gives different results.

**Comment by orschiro** [comment]
Unfortunately the same negative result.

-Robert

![image](https://cloud.githubusercontent.com/assets/170947/18500700/2de2c352-7a4a-11e6-931b-c7806e130c8c.png)

**Comment by oliversalzburg** [comment]
What Ubuntu version are you running and what browser/version?

**Comment by orschiro** [comment]
- Ubuntu 16.04
- Chromium Browser 52.0.2743.116-0ubuntu0.16.04.1.1250

**Comment by oliversalzburg** [comment]
Okay, how do you actually install Chromium on Ubuntu? This is really frustrating >:(

**Comment by orschiro** [comment]
`sudo apt install chromium-browser`

**Comment by oliversalzburg** [comment]
![image](https://cloud.githubusercontent.com/assets/1658949/18513314/523e988c-7a8d-11e6-8cbc-e564a6a20d8e.png)

**Comment by orschiro** [comment]
And this one? 

https://apps.ubuntu.com/cat/applications/chromium-browser/

-Robert

**Comment by oliversalzburg** [comment]
That is not compatible with Ubuntu 16.04. When I click the Download button, I just get an error.

**Comment by orschiro** [comment]
This is very strange. It should be there...

https://launchpad.net/ubuntu/xenial/+source/chromium-browser

:-(

**Comment by oliversalzburg** [comment]
I have no `deb-src` sources, maybe that's the problem.

**Comment by oliversalzburg** [comment]
Alright, [Chromium is installed](http://askubuntu.com/questions/824818/how-can-i-install-chromium-browser-in-live-mode). Now I just need to get the extension installed :D Installing from the web store doesn't work

**Comment by orschiro** [comment]
That's weird, too. 

I had no problems installing your extension from the Chrome Webstore. 

Did you succeed eventually?

-Robert

**Comment by oliversalzburg** [comment]
No. The Web Store tells me I need Chrome to install it. How did you install Chromium? Through apt? Or from google.com/chrome?

**Comment by orschiro** [comment]
I just tried Chrome and the button shows up there!

Let's close this for now. 

I can live with using Chrome for that. 

Thank you for all your help!

-Robert
